INSERT INTO Games(Name, Price, Image) VALUES
('Stellaris: Toxoids Species Pack', 259, 'static.gabestore.ru/product/ri5mPuxfBYStA6Lj_EUto4bZKL1FeF9j.jpg'),
('Cities: Skylines - Content Creator Pack: Mid-Century Modern', 154, 'static.gabestore.ru/product/8CK4zbypjVQXw86YxTFOnBFwe1fwSCrL.jpg'),
('Cities: Skylines - Content Creator Pack: Seaside Resorts', 154, 'static.gabestore.ru/product/zbIO_d8t4v-ROLlCk2jpAsIXo0W0wtVG.jpg'),
('Cities: Skylines - Paradise Radio', 102, 'static.gabestore.ru/product/K2peOhLiaFuWoMSXEObouCynwCVS7Han.jpg'),
('Cities: Skylines - Shoreline Radio', 102, 'static.gabestore.ru/product/ck_vjQ6O6IG5iCt7x2DPk1Plnr30AecE.jpg'),
('Cities: Skylines - Plazas & Promenades', 360, 'static.gabestore.ru/product/rWBlcWXWfdrnbxojsi5HyTvQGo2xwJHo.jpg'),
('Europa Universalis IV: Lions of the North', 360, 'static.gabestore.ru/product/GhK3_Iy_bpeerlAaEwrwenHzP_lGeQkQ.jpg'),
('Lovecrafts Untold Stories 2', 449, 'static.gabestore.ru/product/--hjbgh93N22biwKdT8Y-8pb-h0KtRNB.jpeg'),
('Justice Sucks: Tactical Vacuum Action', 399, 'static.gabestore.ru/product/Rns1Q28deHLKMo3aloO_xmdsRTkOfXQS.jpg'),
('Crusader Kings III: Friends & Foes', 133, 'static.gabestore.ru/product/fp1dxxRYp4D668pjjEbPmkIH4QgbEUYV.jpg'),
('Farming Simulator 17', 449, 'static.gabestore.ru/product/ddjLQsKhz52UU4T7fCiKFzeSY-CyOf9x.jpg'),
('Train Sim World 2', 199, 'static.gabestore.ru/product/RnifWZQ55EbsmcXtKuVRtLj6WfT0DlSg.jpg'),
('Skybolt Zack', 249, 'static.gabestore.ru/product/ZGlDaeAycsgCFTvcbVRMUelmq5zZWRNf.jpg'),
('Keebles', 45, 'static.gabestore.ru/product/Jb1vnUWeD7uYNxbg3dz5kkLie5lfOFmQ.jpg'),
('Idol Hands', 25, 'static.gabestore.ru/product/0P1kys0-9UZ1EWJPsEhcwlG9rwDJob-J.jpg'),
('Glitchrunners', 49, 'static.gabestore.ru/product/fRcPI3WT3Y7FpYi6nhURaNIlVdUehBWw.jpg'),
('Eternal Step', 45, 'static.gabestore.ru/product/Y3p_YsrdD7jZwzeU7EIkasa0mPfWGoxk.jpg'),
('Decisive Campaigns: Case Blue', 349, 'static.gabestore.ru/product/mKH73bdhYNFiSM6IuMkxv5xHeQel3CPm.jpg'),
('Decisive Campaigns: Barbarossa', 599, 'static.gabestore.ru/product/14d8z9iCxLbkQHgHcAhH663fmX0mPek7.jpg'),
('Predator: Hunting Grounds – Cleopatra DLC Pack', 199, 'static.gabestore.ru/product/UBnq-MLPvUiQGfB87_zDQcP7L3O0KKaw.jpg'),
('Model Builder', 299, 'static.gabestore.ru/product/cSxhlCpS8iPCX7R3yEs_7zsEi_9-yaj7.jpg'),
('Switch Galaxy Ultra', 49, 'static.gabestore.ru/product/x3E7G1t8wYEF5HPRHisKwNhL0ujfHMr4.jpg'),
('First Class Trouble Vruumba Pack', 65, 'static.gabestore.ru/product/_bwxMISj-C04XGV1kcVzP7NOw5TCZlPE.jpg'),
('Tank Warfare: Tunisia 1943', 599, 'static.gabestore.ru/product/QbfjPQks0SZvt5qAeVT2_nXdK0zQaN0J.jpg'),
('Steel Fury Kharkov 1942', 129, 'static.gabestore.ru/product/LYfOBeey8-3xomFe7i00R4SYVEGXmC4U.jpg'),
('Space Empires V', 124, 'static.gabestore.ru/product/rsgV2KqwDt-zT1mF1kjmVZAFr9b-7L78.jpg'),
('Mashed', 49, 'static.gabestore.ru/product/_Ikj6hN4VNK4z_bOKQ1VsGxXH5fpH-BW.jpg'),
('Exodus from the Earth', 49, 'static.gabestore.ru/product/EOMeMhKyz-NHyQJXV45ifDdot1RCxddZ.jpg'),
('Clans', 29, 'static.gabestore.ru/product/y9rfVnm7j-rE2f9EfRn84v0XVDMc5UZB.jpg'),
('Farming Simulator 2013 - Official Expansion (Titanium)', 199, 'static.gabestore.ru/product/o_dpo7InFIkNeeH07DYfl7CwMW6GzZkH.jpg')

